### ISSUE TITLE
Unable to upload weblogic cook book

### ISSUE THREAD

**Issue by varunm17** [damacus/weblogic#8]
Hi ,

I am new to chef, i am trying to upload weblogic cookbook and i am getting the below error.

PS C:\chef-repo\cookbooks> knife cookbook upload weblogic
Uploading weblogic       [0.1.6]
ERROR: The data in your request was invalid
Response: Field 'metadata.maintainer' invalid

Is there anything i need to modify before uploading.

Regards,
Varun

**Comment by damacus** [comment]
Hi @varunm17 we've moved this cookbook to https://github.com/universityofderby/chef-weblogic

The new cookbook has a more fleshed out metadata.rb file with the maintainer filled out. 

That should fix your problem.
